### ISSUE TITLE
所以说fcm可能通过这种方式绕过吗😂

### ISSUE THREAD

**Issue by long45343** [Tao0Lu/Arknights-Access-Server#1]
［doge］

**Comment by loinko** [comment]
应该不能 XD

现在鹰角这 HTTPS based 的游戏真是越来越聪明了，去年爬那啥真的特别容易，接口都是暴露的，今天2月份新增了seqnum，最近又实装了 ak-gs-localhost，我这 iOS 抓包真是越抓越难啊

**Comment by Tao0Lu** [comment]
> 应该不能 XD
> 
> 现在鹰角这 HTTPS based 的游戏真是越来越聪明了，去年爬那啥真的特别容易，接口都是暴露的，今天2月份新增了seqnum，最近又实装了 ak-gs-localhost 和 chunked 请求，我这 iOS 抓包真是越抓越难啊

我这里用mitmproxy可以啊。
参考的是[GhostStar/Arknights-Armada](https://github.com/GhostStar/Arknights-Armada)，刚刚测试可以。
<s>或是我fork修改bug后的版本。<s>

**Comment by Tao0Lu** [comment]
> 应该不能 XD
> 
> 现在鹰角这 HTTPS based 的游戏真是越来越聪明了，去年爬那啥真的特别容易，接口都是暴露的，今天2月份新增了seqnum，最近又实装了 ak-gs-localhost 和 chunked 请求，我这 iOS 抓包真是越抓越难啊

我刚抓了一下包有fcm的账户比没有fcm的账户会每隔一段时间多POST一下
有fcm的账户多POST的url为:
https://ak-as.hypergryph.com:9443/online/v1/ping (不能普通的访问，要有header才能访问)
获取的json如下:
{"result":0,"message":"OK","interval":65,"timeLeft":4857,"alertTime":600}
interval为和上次同步fcm的间隔时间戳
timeLeft为剩下的时间的时间戳
所以这就简单的了，修改一下json就可以了

**Comment by loinko** [comment]
确实是可以的....
我今天尝试很多次操作接口都报 invalid version 错误, 刚刚才知道是因为我 secret 把 小写i 打成了 小写L ... 明日方舟的 secret 貌似和版本有联系? ~~(憨憨手打secret)~~

**Comment by Tao0Lu** [comment]
> 啊这，之前说错了确实可以，感谢大佬指正
> 之前说不行是因为我今天尝试很多次操作接口都报 invalid version 错误, 刚刚才知道是因为我 secret 把 小写i 打成了 小写L ... 明日方舟的 secret 貌似和版本有联系? ~(憨憨手打secret)~

好吧。。。
还有，测试了，成功了。
然后写了有个[小程序](https://github.com/Tao0Lu/Arknights_Anti-addiction_Crack)来破解防沉迷。
~~所以我觉得可以关闭issues了~~
